version: '3.8'

services:
  mysql:
    image: mysql:5.6
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1
    environment:
      - MYSQL_DATABASE=sdh_project
      - MYSQL_ROOT_PASSWORD=rower_sdh
      - MYSQL_USER=rower
      - MYSQL_PASSWORD=rower
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    volumes:
      - "./data/mysql:/var/lib/mysql"
